development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: neevtech
  database: smartoncms_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: neevtech
  database: smartoncms_test

production: &production
  adapter: mysql2
  host: localhost
  database: smartoncms_development
  username: root
  password: neevtech
